apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
        - name: mynginxcontainer
          image: raiyan19/myjavaapp09sep13:1
          ports:
            - containerPort: 8080
