apiVersion: v1
kind: Service 
metadata: 
  name: myonliceapp-svc
  labels:
    app: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: mynginx